CFLAGS = "/Fa"

all: ex.c
	cl $(CFLAGS) ex.c
	cmd /C "for %A in (A,B,C,D,E,F,G,H) do @ ex.exe %A" > out.txt
clean:
	del /F /Q *.exe *.obj *.exp *.def *.lib *.asm out.txt check.txt mllink$$.lnk
	del /F /Q ex.unstripped *.s *.old*
	if exist dl_files { rmdir /Q /S dl_files }
check:
	cmd /C "for %A in (A,B,C,D,E,F,G,H) do @ ex.exe %A" > check.txt
	@ FC out.txt check.txt && echo TEST OK
