#
# This assembly was generated by GCC on Ubuntu 18.04 with -O0
# for examples/ex_symbol_selection (and stripped).
#
# $ gcc --version
# gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
#
# The compiler emits a GLOBAL/DEFAULT symbol `_fdata` marking the start of the
# `.data` segment.
# Although `_fdata` has global scope, any reference to the address
# should not use the symbol. Doing so can lead to unexpected runtime behavior,
# for example:
#
# < bar: 0: hello four
# < bar: 1: hello five
# < bar: 2: hello six
# ---
# > bar: 0: (null)
# > bar: 1: (null)
# > bar: 2: (null)
#
# This test ensures that correct symbolic expressions are generated at the
# `lw`/`addiu` instruction pair using `%got_page` and `%got_ofst`.
#
.set noreorder

#===================================
.text
#===================================

.align 4
#-----------------------------------
.globl bar
.type bar, @function
#-----------------------------------
bar:

            lui $gp,%hi(_gp_disp)
            addiu $gp,$gp,%lo(_gp_disp)
            addu $gp,$gp,$t9
            addiu $sp,$sp,-40
            sw $ra,36($sp)
            sw $fp,32($sp)
            move $fp,$sp
            sw $gp,16($sp)
            sw $zero,28($fp)
            b .L_814
            nop
.L_7cc:

            lw $v0,%got_page(.data)($gp)
            lw $v1,28($fp)
            sll $v1,$v1,2
            addiu $v0,$v0,%got_ofst(.data)
            addu $v0,$v1,$v0
            lw $v0,0($v0)
            move $a2,$v0
            lw $a1,28($fp)
            lw $v0,%got_page(.L_9d4)($gp)
            addiu $a0,$v0,%got_ofst(.L_9d4)
            lw $v0,%got(printf)($gp)
            move $t9,$v0
            jalr $t9
            nop

            lw $gp,16($fp)
            lw $v0,28($fp)
            addiu $v0,$v0,1
            sw $v0,28($fp)
.L_814:

            lw $v0,28($fp)
            slti $v0,$v0,3
            bnez $v0,.L_7cc
            nop

            nop
            move $sp,$fp
            lw $ra,36($sp)
            lw $fp,32($sp)
            addiu $sp,$sp,40
            jr $ra
            nop
.size bar, . - bar
.align 4
#-----------------------------------
.globl fun
.type fun, @function
#-----------------------------------
fun:

            lui $gp,%hi(_gp_disp)
            addiu $gp,$gp,%lo(_gp_disp)
            addu $gp,$gp,$t9
            addiu $sp,$sp,-40
            sw $ra,36($sp)
            sw $fp,32($sp)
            move $fp,$sp
            sw $gp,16($sp)
            sw $zero,28($fp)
            sw $zero,28($fp)
            b .L_8b4
            nop
.L_870:

            lw $v1,%got(my_strings)($gp)
            lw $v0,28($fp)
            sll $v0,$v0,2
            addu $v0,$v1,$v0
            lw $v0,0($v0)
            move $a2,$v0
            lw $a1,28($fp)
            lw $v0,%got_page(.L_a20)($gp)
            addiu $a0,$v0,%got_ofst(.L_a20)
            lw $v0,%got(printf)($gp)
            move $t9,$v0
            jalr $t9
            nop

            lw $gp,16($fp)
            lw $v0,28($fp)
            addiu $v0,$v0,1
            sw $v0,28($fp)
.L_8b4:

            lw $v0,28($fp)
            slti $v0,$v0,3
            bnez $v0,.L_870
            nop

            nop
            move $sp,$fp
            lw $ra,36($sp)
            lw $fp,32($sp)
            addiu $sp,$sp,40
            jr $ra
            nop
.size fun, . - fun
#===================================
# end section .text
#===================================

#===================================
.section .rodata ,"a",@progbits
#===================================

.align 4
.L_9b0:
          .string "hello four"
          .zero 1
.L_9bc:
          .string "hello five"
          .zero 1
.L_9c8:
          .string "hello six"
          .zero 2
#-----------------------------------
.globl .L_9d4
.hidden .L_9d4
.type .L_9d4, @notype
#-----------------------------------
.L_9d4:
          .string "bar: %d: %s\n"
          .zero 15
.L_9f0:
          .string "hello one"
          .zero 2
.L_9fc:
          .string "hello two"
          .zero 2
.L_a08:
          .string "hello three"
          .zero 12
#-----------------------------------
.globl .L_a20
.hidden .L_a20
.type .L_a20, @notype
#-----------------------------------
.L_a20:
          .string "fun: %d: %s\n"
          .zero 3
#===================================
# end section .rodata
#===================================

#===================================
.data
#===================================

.align 4
#-----------------------------------
.globl _fdata
.type _fdata, @notype
#-----------------------------------
_fdata:
          .long .L_9b0
          .long .L_9bc
          .long .L_9c8
          .zero 4
#-----------------------------------
.globl my_strings
.type my_strings, @object
.size my_strings, 12
#-----------------------------------
my_strings:
          .long .L_9f0
          .long .L_9fc
          .long .L_a08
          .zero 4
#===================================
# end section .data
#===================================

#===================================
.section .sdata ,"wa",@progbits
#===================================

.align 2
#-----------------------------------
.globl .L_11060
.hidden .L_11060
.type .L_11060, @notype
#-----------------------------------
.L_11060:
          .long .L_11060
#===================================
# end section .sdata
#===================================

#===================================
.bss
#===================================

.align 4
#-----------------------------------
.globl _fbss
.type _fbss, @notype
#-----------------------------------
_fbss:
#-----------------------------------
.globl .L_11070
.hidden .L_11070
.type .L_11070, @notype
#-----------------------------------
.L_11070:
          .zero 4
#-----------------------------------
.globl .L_11074
.hidden .L_11074
.type .L_11074, @notype
#-----------------------------------
.L_11074:
          .zero 12
#===================================
# end section .bss
#===================================
