FROM ubuntu:18.04

RUN apt-get update \
    && apt-get -y install \
    python3 \
    python3-pip \
    clang-format \
    git \
    curl

RUN pip3 install pre-commit

COPY . /ddisasm
WORKDIR /ddisasm

# cdonfigure pre-commit, so Docker caches the configuration step.
# This invocation won't actually run formatters on any files.
RUN pre-commit run; echo "Configured pre-commit."

# Actually run pre-commit, reporting an error if any file needs formatted.
CMD pre-commit run --all-files
