FROM ubuntu:18.04 AS test-base

# Use bash for more convenient variable substitution syntax
SHELL ["/bin/bash", "-c"]

# dpkg-dev: for dpkg-scanpackages
# software-properties-common: for add-apt-repository
RUN apt-get -y update && apt-get -y install curl dpkg-dev software-properties-common \
    unzip

# for boost 1.67
RUN add-apt-repository ppa:mhier/libboost-latest

# setup apt repository
COPY ddisasm*.deb /gt/apt-repo/
COPY libcapstone-dev_*_amd64.deb /gt/apt-repo/
COPY gtirb-ubuntu18-artifacts.zip /gt/apt-repo/
COPY gtirb-pprinter-ubuntu18-artifacts.zip /gt/apt-repo/
WORKDIR /gt/apt-repo/
RUN unzip -o /gt/apt-repo/gtirb-ubuntu18-artifacts.zip
RUN unzip -o /gt/apt-repo/gtirb-pprinter-ubuntu18-artifacts.zip
RUN cd /gt/apt-repo && dpkg-scanpackages . /dev/null > Packages

# Add the local repository
RUN echo $'\ndeb [trusted=yes] file:/gt/apt-repo ./\n' >> /etc/apt/sources.list
RUN apt-get update -y

# install & test ddisasm
FROM test-base AS test-ddisasm
RUN apt-get install -y ddisasm
RUN ddisasm --version

# test debug package
FROM test-base AS test-debug
RUN apt-get install -y --allow-unauthenticated ddisasm-dbg
RUN [ -f /usr/lib/debug/.build-id/$(readelf -n /usr/bin/ddisasm | grep 'Build ID: ' | cut -d":" -f2 | sed -E 's/ ([a-f0-9]{2,})([a-f0-9]{30,})/\1\/\2/g').debug ]
