FROM ubuntu:18.04

RUN apt-get update \
    && apt-get -y install \
    python3 \
    python3-pip \
    clang-format \
    git \
    curl

RUN pip3 install pre-commit 'six>1.12.0'

COPY . /ddisasm
WORKDIR /ddisasm

RUN pre-commit run --all-files
