ARG IMAGE="docker.grammatech.com/rewriting/ddisasm/ubuntu18-gcc"
FROM $IMAGE

WORKDIR /ddisasm/build
RUN dpkg -i DDISASM-*-Linux.deb
WORKDIR /
RUN rm -rf /ddisasm/build
RUN LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/ddisasm/gtirb-pprinter/build/lib:/ddisasm/libehp/build/lib:/usr/local/lib ddisasm --help || test $? -eq 1
