CFLAGS="/Fa"

all: ex.c
	cl /nologo $(CFLAGS) ex.c
	@ echo A |ex > out.txt
	@ echo B |ex >> out.txt
	@ echo C |ex >> out.txt
clean:
	del /F /Q *.exe *.obj *.exp *.def *.lib *.s out.txt check.txt mllink$$.lnk
check:
	@ echo A |ex > check.txt
	@ echo B |ex >> check.txt
	@ echo C |ex >> check.txt
	@ FC out.txt check.txt && echo TEST OK
