CFLAGS = "/Fa"

all: main.c
	cl $(CFLAGS) main.c
	cmd /C "for %A in (750 800 900 700 500 250 100 200 600) do @ main.exe %A" > out.txt
clean:
	del /F /Q *.exe *.obj *.exp *.def *.lib *.asm out.txt check.txt mllink$$.lnk
	del /F /Q ex.unstripped *.s *.old*
	if exist dl_files { rmdir /Q /S dl_files }
check:
	cmd /C "for %A in (750 800 900 700 500 250 100 200 600) do @ main.exe %A" > check.txt
	@ FC out.txt check.txt && echo TEST OK
