CFLAGS = "/Fa"

all: ex.c
	cl $(CFLAGS) ex.c
	cmd /C "for %A in (A,B,C,D,E,F,G,H,I,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z) do @ ex.exe %A" > out.txt
clean:
	del /F /Q *.exe *.obj *.exp *.def *.lib *.s out.txt check.txt mllink$$.lnk
check:
	cmd /C "for %A in (A,B,C,D,E,F,G,H,I,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z) do @ ex.exe %A" > check.txt
	@ FC out.txt check.txt && echo TEST OK
