CFLAGS=""

all: ex.c
	cl /nologo $(CFLAGS) ex.c
	@ ex > out.txt
clean:
	del /F /Q *.exe *.obj *.exp *.def *.lib *.s out.txt check.txt mllink$$.lnk
check:
	@ ex >check.txt
	@ FC out.txt check.txt && echo TEST OK
