CFLAGS="/Fa"

all: ex.res ex.c
	cl /nologo $(CFLAGS) ex.c /link ex.res
	@ ex > out.txt
ex.res: ex.rc
	rc /nologo ex.rc
clean:
	del /F /Q *.exe *.obj *.exp *.def *.lib *.asm *.res out.txt check.txt mllink$$.lnk
	del /F /Q ex.unstripped *.s *.old*
	if exist dl_files { rmdir /Q /S dl_files }
check:
	@ ex >check.txt
	@ FC out.txt check.txt && echo TEST OK
